services:
  api:
    restart: on-failure:5
    build:
      context: backend
      dockerfile: Dockerfile
      target: production
    ports:
      - 8080:8080
    environment:
      - ENV=prod
      - SQLITE_PATH=${SQLITE_PATH?}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY?}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT?}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME?}
    networks:
      - insighty
    volumes:
      - sqlite-insighty:/data

  web:
    build:
      context: frontend
      target: production
    networks:
      - insighty
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

volumes:
  sqlite-insighty:
    name: sqlite-insighty

networks:
  insighty: